"""LLM-assisted cold outreach email drafting tailored to candidate resume profile."""

import json
import logging
import re
from dataclasses import dataclass

from jobpilot.llm.client import BaseLLMClient, get_llm_client
from jobpilot.resume.extractor import StructuredResumeProfile

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ColdEmailDraft:
    """Structured cold email draft generated by LLM."""

    subject: str
    body: str


COLD_EMAIL_PROMPT_TEMPLATE = """You are an expert career mentor helping an \
exceptional software engineering student reach out to a recruiter or engineering manager.

Write a personalized, high-converting cold email for this candidate applying to the company & role.

CANDIDATE BACKGROUND:
Target Roles: {target_roles}
Top Skills: {skills}
Domain Focus: {domains}
Project Highlights: {projects}
Summary: {summary}

APPLICATION DETAILS:
Company: {company}
Role: {role}

REQUIREMENTS:
1. Subject line: Punchy, concise (e.g., "[School/Name] - [Role] Interest & [Top Project]").
2. Body: Exactly 3-4 crisp sentences.
   - Sentence 1: Mention recent application for [Role] at [Company] and genuine interest.
   - Sentence 2-3: Highlight 1 specific relevant technical project or skill aligning with company.
   - Sentence 4: Low-friction call to action (e.g. quick 5-minute chat next week).
3. Tone: Professional, enthusiastic, student-friendly, zero fluff or generic buzzwords.
4. Output Format: Strict JSON matching the schema below:
{{
  "subject": "Subject line text",
  "body": "Email body text (with appropriate line breaks)"
}}
"""


class ColdEmailDrafter:
    """Generates tailored cold emails using candidate resume profile and target role."""

    def __init__(self, llm_client: BaseLLMClient | None = None) -> None:
        self.llm_client = llm_client or get_llm_client()

    def _clean_json_response(self, text: str) -> str:
        """Strip markdown code blocks and whitespace from LLM output."""
        cleaned = text.strip()
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
        return cleaned.strip()

    async def generate_draft(
        self,
        profile: StructuredResumeProfile | None = None,
        company_name: str = "",
        role_title: str | None = None,
        candidate_profile: StructuredResumeProfile | None = None,
    ) -> ColdEmailDraft:
        """Generate a personalized cold outreach email draft."""
        active_profile = profile or candidate_profile
        role = role_title or "Software Engineer Intern"
        skills = (
            ", ".join(active_profile.skills[:6])
            if active_profile and active_profile.skills
            else "Python, TypeScript"
        )
        domains = (
            ", ".join(active_profile.domains[:4])
            if active_profile and active_profile.domains
            else "Software Engineering, AI"
        )
        projects = (
            ", ".join(active_profile.project_themes[:2])
            if active_profile and active_profile.project_themes
            else "Full-stack and ML systems"
        )
        target_roles = (
            ", ".join(active_profile.target_roles[:2])
            if active_profile and active_profile.target_roles
            else "Software Engineer"
        )
        summary = (
            active_profile.summary
            if active_profile and active_profile.summary
            else "Computer Science student"
        )

        prompt = COLD_EMAIL_PROMPT_TEMPLATE.format(
            target_roles=target_roles,
            skills=skills,
            domains=domains,
            projects=projects,
            summary=summary,
            company=company_name,
            role=role,
        )

        for attempt in range(2):
            try:
                raw_response = await self.llm_client.generate(prompt)
                cleaned = self._clean_json_response(raw_response)
                data = json.loads(cleaned)
                subject = data.get("subject", f"Interest in {role} at {company_name}")
                body = data.get("body", "")
                if body.strip():
                    return ColdEmailDraft(subject=subject, body=body.strip())
            except Exception as exc:
                logger.warning(
                    "Cold email drafting attempt %d failed: %s",
                    attempt + 1,
                    exc,
                )

        # Fallback template
        fallback_subject = f"Interest in {role} at {company_name}"
        fallback_body = (
            f"Hi team,\n\n"
            f"I recently applied for the {role} position at {company_name} and wanted to "
            f"reach out. With hands-on experience in {skills}, I have built projects focused on "
            f"{projects}. I'm very excited about {company_name}'s mission and would love to "
            f"connect briefly if you have any time.\n\n"
            f"Best regards,"
        )
        return ColdEmailDraft(subject=fallback_subject, body=fallback_body)

    draft = generate_draft
